import { ConfigurationDomainGroup } from "@/types/configuration";

export const INITIAL_DOMAINS_DATA: ConfigurationDomainGroup[] = [
	{
		category: "GENERAL",
		categoryLabel: "General",
		description:
			"System-wide parameters, localization, timezone, and operational formats.",
		icon: "Settings",
		displayOrder: 1,
		totalConfigurations: 7,
		sections: [
			{
				sectionName: "Localization & Formatting",
				configurations: [
					{
						id: 101,
						configKey: "system.timezone",
						label: "Primary System Timezone",
						configValue: "Asia/Phnom_Penh",
						valueType: "STRING",
						scope: "COMPANY",
						category: "GENERAL",
						uiComponent: "SELECT",
						options: JSON.stringify([
							"Asia/Phnom_Penh",
							"Asia/Bangkok",
							"UTC",
							"America/New_York",
							"Europe/London",
						]),
						defaultValue: "Asia/Phnom_Penh",
						description: "Default timezone for timestamps and scheduled jobs",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 1,
						overridden: false,
					},
					{
						id: 102,
						configKey: "system.date_format",
						label: "Standard Date Format",
						configValue: "YYYY-MM-DD",
						valueType: "STRING",
						scope: "COMPANY",
						category: "GENERAL",
						uiComponent: "SELECT",
						options: JSON.stringify(["YYYY-MM-DD", "DD/MM/YYYY", "MM/DD/YYYY"]),
						defaultValue: "YYYY-MM-DD",
						description:
							"Format used to display dates across reports and invoices",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 2,
						overridden: false,
					},
					{
						id: 103,
						configKey: "system.currency",
						label: "Default Operational Currency",
						configValue: "USD",
						valueType: "STRING",
						scope: "COMPANY",
						category: "GENERAL",
						uiComponent: "SELECT",
						options: JSON.stringify(["USD", "KHR", "EUR", "THB"]),
						defaultValue: "USD",
						description: "Primary currency for accounting ledgers and pricing",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 3,
						overridden: false,
					},
					{
						id: 104,
						configKey: "system.language",
						label: "Default Interface Language",
						configValue: "en",
						valueType: "STRING",
						scope: "COMPANY",
						category: "GENERAL",
						uiComponent: "SELECT",
						options: JSON.stringify([
							{ label: "English (US)", value: "en" },
							{ label: "Khmer (ភាសាខ្មែរ)", value: "km" },
							{ label: "Chinese (中文)", value: "zh" },
						]),
						defaultValue: "en",
						description: "Default fallback locale for new users",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 4,
						overridden: false,
					},
				],
			},
			{
				sectionName: "System Operations",
				configurations: [
					{
						id: 105,
						configKey: "system.maintenance_mode",
						label: "Maintenance Mode",
						configValue: false,
						valueType: "BOOLEAN",
						scope: "SYSTEM",
						category: "GENERAL",
						uiComponent: "TOGGLE",
						defaultValue: "false",
						description:
							"Temporarily disables user access for scheduled maintenance",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: true,
						displayOrder: 1,
						overridden: false,
					},
					{
						id: 106,
						configKey: "system.debug_logging",
						label: "Verbose Audit Logging",
						configValue: false,
						valueType: "BOOLEAN",
						scope: "SYSTEM",
						category: "GENERAL",
						uiComponent: "TOGGLE",
						defaultValue: "false",
						description:
							"Enables detailed API request / response payload tracing",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: true,
						displayOrder: 2,
						overridden: false,
					},
					{
						id: 107,
						configKey: "system.api_rate_limit",
						label: "API Rate Limit (Req / Min)",
						configValue: 120,
						valueType: "INTEGER",
						scope: "SYSTEM",
						category: "GENERAL",
						uiComponent: "NUMBER",
						validationRule: "10..1000",
						defaultValue: "120",
						description:
							"Maximum API requests permitted per user token per minute",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: true,
						displayOrder: 3,
						overridden: false,
					},
				],
			},
		],
	},
	{
		category: "SECURITY",
		categoryLabel: "Security",
		description:
			"Company security policies, login protection, session lifetimes and admin-only rules.",
		icon: "ShieldAlert",
		displayOrder: 2,
		totalConfigurations: 6,
		sections: [
			{
				sectionName: "Login Protection",
				configurations: [
					{
						id: 201,
						configKey: "security.max_login_attempts",
						label: "Maximum Failed Login Attempts",
						configValue: 5,
						valueType: "INTEGER",
						scope: "COMPANY",
						category: "SECURITY",
						uiComponent: "NUMBER",
						validationRule: "1..20",
						defaultValue: "5",
						description:
							"Number of consecutive incorrect passwords before temporary lockout",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 1,
						overridden: false,
					},
					{
						id: 202,
						configKey: "security.lockout_duration_mins",
						label: "Account Lockout Duration (Minutes)",
						configValue: 30,
						valueType: "INTEGER",
						scope: "COMPANY",
						category: "SECURITY",
						uiComponent: "NUMBER",
						validationRule: "5..1440",
						defaultValue: "30",
						description:
							"Duration a locked user account must wait before re-attempting login",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 2,
						overridden: false,
					},
					{
						id: 203,
						configKey: "security.two_factor_auth_enforced",
						label: "Enforce 2FA for Staff Accounts",
						configValue: true,
						valueType: "BOOLEAN",
						scope: "SYSTEM",
						category: "SECURITY",
						uiComponent: "TOGGLE",
						defaultValue: "false",
						description:
							"Require TOTP / Authenticator App for all company operators",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: true,
						displayOrder: 3,
						overridden: true,
					},
					{
						id: 204,
						configKey: "security.password_min_length",
						label: "Minimum Password Length",
						configValue: 8,
						valueType: "INTEGER",
						scope: "COMPANY",
						category: "SECURITY",
						uiComponent: "NUMBER",
						validationRule: "8..32",
						defaultValue: "8",
						description: "Minimum character length required for user passwords",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 4,
						overridden: false,
					},
				],
			},
			{
				sectionName: "Session & IP Whitelist",
				configurations: [
					{
						id: 205,
						configKey: "security.session_timeout_minutes",
						label: "Session Inactivity Timeout (Minutes)",
						configValue: 60,
						valueType: "INTEGER",
						scope: "COMPANY",
						category: "SECURITY",
						uiComponent: "NUMBER",
						validationRule: "15..480",
						defaultValue: "60",
						description:
							"Idle duration after which user session automatically expires",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 1,
						overridden: false,
					},
					{
						id: 206,
						configKey: "security.ip_whitelist",
						label: "Allowed Admin IP Ranges (CIDR)",
						configValue: ["10.0.0.0/24", "192.168.1.100"],
						valueType: "JSON",
						scope: "COMPANY",
						category: "SECURITY",
						uiComponent: "TAGS",
						defaultValue: '["10.0.0.0/24"]',
						description:
							"IP addresses or subnets permitted to perform administrative actions",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 2,
						overridden: true,
					},
				],
			},
		],
	},
	{
		category: "INVENTORY",
		categoryLabel: "Inventory & Stock",
		description:
			"Warehouse rules, negative stock policies, and fulfillment thresholds.",
		icon: "Boxes",
		displayOrder: 3,
		totalConfigurations: 7,
		sections: [
			{
				sectionName: "Stock Policy",
				configurations: [
					{
						id: 301,
						configKey: "inventory.allow_negative_stock",
						label: "Allow Negative Stock",
						configValue: false,
						valueType: "BOOLEAN",
						scope: "SYSTEM",
						category: "INVENTORY",
						uiComponent: "TOGGLE",
						defaultValue: "false",
						description:
							"Permit warehouse orders to deplete quantities below zero",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: true,
						displayOrder: 1,
						overridden: true,
					},
					{
						id: 302,
						configKey: "inventory.allow_correspondence_stock",
						label: "Allow Correspner Stock",
						configValue: false,
						valueType: "BOOLEAN",
						scope: "COMPANY",
						category: "INVENTORY",
						uiComponent: "TOGGLE",
						defaultValue: "false",
						description:
							"Allow cross-branch stock matching without reservation lock",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 2,
						overridden: false,
					},
					{
						id: 303,
						configKey: "inventory.allow_nonexpensive_stock",
						label: "Allow Nonispentive Stock",
						configValue: false,
						valueType: "BOOLEAN",
						scope: "COMPANY",
						category: "INVENTORY",
						uiComponent: "TOGGLE",
						defaultValue: "false",
						description:
							"Bypass valuation checks for low-cost consumable items",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 3,
						overridden: false,
					},
					{
						id: 304,
						configKey: "inventory.auto_reserve_stock",
						label: "Auto Reserve Stock on Order Placement",
						configValue: true,
						valueType: "BOOLEAN",
						scope: "COMPANY",
						category: "INVENTORY",
						uiComponent: "TOGGLE",
						defaultValue: "true",
						description:
							"Automatically place hold on inventory upon order draft submission",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 4,
						overridden: false,
					},
				],
			},
			{
				sectionName: "Alerts & Thresholds",
				configurations: [
					{
						id: 305,
						configKey: "inventory.low_stock_threshold",
						label: "Low Stock Warning Threshold",
						configValue: 10,
						valueType: "INTEGER",
						scope: "COMPANY",
						category: "INVENTORY",
						uiComponent: "NUMBER",
						validationRule: "0..500",
						defaultValue: "10",
						description:
							"Item count at which low-stock notifications are dispatched",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 1,
						overridden: false,
					},
					{
						id: 306,
						configKey: "inventory.critical_stock_threshold",
						label: "Critical Out-of-Stock Level",
						configValue: 3,
						valueType: "INTEGER",
						scope: "COMPANY",
						category: "INVENTORY",
						uiComponent: "NUMBER",
						validationRule: "0..100",
						defaultValue: "3",
						description:
							"Critical threshold triggering purchase replenishment alerts",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 2,
						overridden: false,
					},
					{
						id: 307,
						configKey: "inventory.default_warehouse_code",
						label: "Default Warehouse Code",
						configValue: "WH-MAIN",
						valueType: "STRING",
						scope: "COMPANY",
						category: "INVENTORY",
						uiComponent: "TEXT",
						defaultValue: "WH-MAIN",
						description:
							"Default fulfillment warehouse for newly registered products",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 3,
						overridden: false,
					},
				],
			},
		],
	},
	{
		category: "DOCUMENT",
		categoryLabel: "Documents",
		description:
			"Prefixes, auto-numbering, layout headers, and template styling.",
		icon: "FileText",
		displayOrder: 4,
		totalConfigurations: 7,
		sections: [
			{
				sectionName: "Invoice Numbering",
				configurations: [
					{
						id: 401,
						configKey: "invoice.prefix",
						label: "Prefix (e.g., INV-)",
						configValue: "INV-",
						valueType: "STRING",
						scope: "COMPANY",
						category: "DOCUMENT",
						uiComponent: "TEXT",
						defaultValue: "INV-",
						description: "Prefix prepended to customer sales invoices",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 1,
						overridden: false,
					},
					{
						id: 402,
						configKey: "invoice.credit_note_prefix",
						label: "Prefix (e.g., ILV-)",
						configValue: "ILV-",
						valueType: "STRING",
						scope: "COMPANY",
						category: "DOCUMENT",
						uiComponent: "TEXT",
						defaultValue: "ILV-",
						description:
							"Prefix for credit notes, returns, and inventory loan vouchers",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 2,
						overridden: false,
					},
					{
						id: 403,
						configKey: "invoice.start_sequence",
						label: "Starting Sequence Number",
						configValue: 1001,
						valueType: "INTEGER",
						scope: "COMPANY",
						category: "DOCUMENT",
						uiComponent: "NUMBER",
						validationRule: "1000..999999",
						defaultValue: "1001",
						description: "Initial numeric counter for invoice sequencing",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 3,
						overridden: false,
					},
					{
						id: 404,
						configKey: "invoice.auto_generation",
						label: "Auto Generate Sequence on Finalize",
						configValue: true,
						valueType: "BOOLEAN",
						scope: "COMPANY",
						category: "DOCUMENT",
						uiComponent: "TOGGLE",
						defaultValue: "true",
						description:
							"Assign official consecutive sequence number when invoice is confirmed",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 4,
						overridden: false,
					},
				],
			},
			{
				sectionName: "Invoice Template & Brand",
				configurations: [
					{
						id: 405,
						configKey: "invoice.theme_color",
						label: "Invoice Header Accent Color",
						configValue: "#2563EB",
						valueType: "STRING",
						scope: "COMPANY",
						category: "DOCUMENT",
						uiComponent: "COLOR_PICKER",
						defaultValue: "#2563EB",
						description:
							"Accent color applied on PDF receipts and web payment previews",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 1,
						overridden: true,
					},
					{
						id: 406,
						configKey: "invoice.tax_rate_percentage",
						label: "Standard VAT / Tax Rate (%)",
						configValue: 10.0,
						valueType: "DECIMAL",
						scope: "COMPANY",
						category: "DOCUMENT",
						uiComponent: "DECIMAL",
						defaultValue: "10.0",
						description: "Default percentage applied to taxable sales items",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 2,
						overridden: false,
					},
				],
			},
			{
				sectionName: "Visit Tracking",
				configurations: [
					{
						id: 407,
						configKey: "customer.visit_status_thresholds",
						label: "Visit Status & Map Pin Colors",
						configValue: [
							{
								label: "ថ្ងៃនេះ",
								color: "#FF8C00",
								icon: "🟠",
								minDays: 0,
								maxDays: 1,
								priority: 1,
							},
							{
								label: "១ សប្ដាហ៍ ",
								color: "#22C55E",
								icon: "🟢",
								minDays: 2,
								maxDays: 13,
								priority: 2,
							},
							{
								label: "២ សប្ដាហ៍ ",
								color: "#3B82F6",
								icon: "🔵",
								minDays: 14,
								maxDays: 29,
								priority: 3,
							},
							{
								label: "១ ខែ ",
								color: "#EAB308",
								icon: "🟡",
								minDays: 30,
								maxDays: 89,
								priority: 4,
							},
							{
								label: "៣ ខែ ",
								color: "#EF4444",
								icon: "🔴",
								minDays: 90,
								maxDays: 179,
								priority: 5,
							},
							{
								label: "៦ ខែ ",
								color: "#1F2937",
								icon: "⬛",
								minDays: 180,
								maxDays: 2147483647,
								priority: 6,
							},
						],
						valueType: "JSON",
						scope: "COMPANY",
						category: "CUSTOMER",
						uiComponent: "JSON_EDITOR",
						defaultValue: JSON.stringify([
							{
								label: "ថ្ងៃនេះ",
								color: "#FF8C00",
								icon: "🟠",
								minDays: 0,
								maxDays: 1,
								priority: 1,
							},
							{
								label: "១ សប្ដាហ៍ ",
								color: "#22C55E",
								icon: "🟢",
								minDays: 2,
								maxDays: 13,
								priority: 2,
							},
							{
								label: "២ សប្ដាហ៍ ",
								color: "#3B82F6",
								icon: "🔵",
								minDays: 14,
								maxDays: 29,
								priority: 3,
							},
							{
								label: "១ ខែ ",
								color: "#EAB308",
								icon: "🟡",
								minDays: 30,
								maxDays: 89,
								priority: 4,
							},
							{
								label: "៣ ខែ ",
								color: "#EF4444",
								icon: "🔴",
								minDays: 90,
								maxDays: 179,
								priority: 5,
							},
							{
								label: "៦ ខែ ",
								color: "#1F2937",
								icon: "⬛",
								minDays: 180,
								maxDays: 2147483647,
								priority: 6,
							},
						]),
						description:
							"Define threshold intervals and visual pin colors used across the customer activity map",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 3,
						overridden: false,
					},
				],
			},
		],
	},
	{
		category: "AUTH",
		categoryLabel: "Auth",
		description: "Single sign-on, JWT token expirations, and OAuth providers.",
		icon: "Lock",
		displayOrder: 5,
		totalConfigurations: 5,
		sections: [
			{
				sectionName: "Token Configuration",
				configurations: [
					{
						id: 501,
						configKey: "auth.access_token_expiry_minutes",
						label: "Access Token Lifetime (Minutes)",
						configValue: 60,
						valueType: "INTEGER",
						scope: "COMPANY",
						category: "AUTH",
						uiComponent: "NUMBER",
						validationRule: "5..1440",
						defaultValue: "60",
						description:
							"Duration before access JWT expires and requires refresh token",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 1,
						overridden: false,
					},
					{
						id: 502,
						configKey: "auth.refresh_token_expiry_days",
						label: "Refresh Token Lifetime (Days)",
						configValue: 30,
						valueType: "INTEGER",
						scope: "COMPANY",
						category: "AUTH",
						uiComponent: "NUMBER",
						validationRule: "1..90",
						defaultValue: "30",
						description:
							"Maximum offline session duration before forcing full re-login",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 2,
						overridden: false,
					},
					{
						id: 503,
						configKey: "auth.allow_multiple_sessions",
						label: "Allow Concurrent User Sessions",
						configValue: true,
						valueType: "BOOLEAN",
						scope: "COMPANY",
						category: "AUTH",
						uiComponent: "TOGGLE",
						defaultValue: "true",
						description:
							"Permit users to be logged in simultaneously on mobile & desktop",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 3,
						overridden: false,
					},
				],
			},
			{
				sectionName: "Federation & Social SSO",
				configurations: [
					{
						id: 504,
						configKey: "auth.google_sso_enabled",
						label: "Enable Google Workspace SSO",
						configValue: true,
						valueType: "BOOLEAN",
						scope: "COMPANY",
						category: "AUTH",
						uiComponent: "TOGGLE",
						defaultValue: "true",
						description:
							"Allow organization members to authenticate with corporate Google emails",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 1,
						overridden: false,
					},
					{
						id: 505,
						configKey: "auth.oauth_allowed_domains",
						label: "Restricted OAuth Email Domains",
						configValue: ["rumluos.com"],
						valueType: "JSON",
						scope: "COMPANY",
						category: "AUTH",
						uiComponent: "TAGS",
						defaultValue: '["rumluos.com"]',
						description:
							"Only email addresses under these domains may log in via SSO",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 2,
						overridden: true,
					},
				],
			},
		],
	},
	{
		category: "WORKFLOW",
		categoryLabel: "Workflow",
		description:
			"Multi-level approval pipelines, threshold limits, and notification rules.",
		icon: "Layers",
		displayOrder: 6,
		totalConfigurations: 4,
		sections: [
			{
				sectionName: "Approval Thresholds",
				configurations: [
					{
						id: 701,
						configKey: "workflow.multi_level_approval",
						label: "Multi-Level Order Approvals",
						configValue: true,
						valueType: "BOOLEAN",
						scope: "COMPANY",
						category: "WORKFLOW",
						uiComponent: "TOGGLE",
						defaultValue: "true",
						description:
							"Enforce manager authorization on high-value quotes & purchase orders",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 1,
						overridden: false,
					},
					{
						id: 702,
						configKey: "workflow.manager_approval_threshold",
						label: "Manager Approval Min Amount ($)",
						configValue: 1000.0,
						valueType: "DECIMAL",
						scope: "COMPANY",
						category: "WORKFLOW",
						uiComponent: "DECIMAL",
						defaultValue: "1000.00",
						description:
							"Orders exceeding this value require Sales Manager confirmation",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 2,
						overridden: false,
					},
					{
						id: 703,
						configKey: "workflow.director_approval_threshold",
						label: "Director Approval Min Amount ($)",
						configValue: 10000.0,
						valueType: "DECIMAL",
						scope: "COMPANY",
						category: "WORKFLOW",
						uiComponent: "DECIMAL",
						defaultValue: "10000.00",
						description:
							"High-value deals requiring executive director authorization",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 3,
						overridden: false,
					},
				],
			},
			{
				sectionName: "Workflow Schema Rules",
				configurations: [
					{
						id: 704,
						configKey: "workflow.approval_chain_config",
						label: "Workflow Chain Rules JSON",
						configValue: {
							enabled: true,
							levels: [
								{ level: 1, role: "Stockkeeper", minAmount: 0, required: true },
								{
									level: 2,
									role: "Sales Manager",
									minAmount: 1000,
									required: true,
								},
								{
									level: 3,
									role: "Finance Director",
									minAmount: 10000,
									required: false,
								},
							],
						},
						valueType: "JSON",
						scope: "COMPANY",
						category: "WORKFLOW",
						uiComponent: "JSON_EDITOR",
						defaultValue: JSON.stringify({
							enabled: true,
							levels: [
								{ level: 1, role: "Stockkeeper", minAmount: 0, required: true },
								{
									level: 2,
									role: "Sales Manager",
									minAmount: 1000,
									required: true,
								},
								{
									level: 3,
									role: "Finance Director",
									minAmount: 10000,
									required: false,
								},
							],
						}),
						description: "Hierarchical approval rules schema JSON definition",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 1,
						overridden: false,
					},
				],
			},
		],
	},
	{
		category: "FINANCE",
		categoryLabel: "Finance",
		description:
			"Payment gateway credentials, KHQR Bakong integration, and transaction parameters.",
		icon: "CreditCard",
		displayOrder: 7,
		totalConfigurations: 4,
		sections: [
			{
				sectionName: "Payment Gateways & KHQR",
				configurations: [
					{
						id: 801,
						configKey: "finance.enable_aba_khqr",
						label: "Enable ABA PayWay KHQR Integration",
						configValue: true,
						valueType: "BOOLEAN",
						scope: "COMPANY",
						category: "FINANCE",
						uiComponent: "TOGGLE",
						defaultValue: "true",
						description:
							"Direct instant payment via NBC Bakong KHQR QR-code standard",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 1,
						overridden: false,
					},
					{
						id: 802,
						configKey: "finance.enable_stripe",
						label: "Enable Stripe Credit Card Gateway",
						configValue: false,
						valueType: "BOOLEAN",
						scope: "COMPANY",
						category: "FINANCE",
						uiComponent: "TOGGLE",
						defaultValue: "false",
						description:
							"Accept Visa, MasterCard, and international debit cards",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 2,
						overridden: false,
					},
					{
						id: 803,
						configKey: "finance.default_gateway",
						label: "Primary Payment Gateway",
						configValue: "ABA_PAY",
						valueType: "STRING",
						scope: "COMPANY",
						category: "FINANCE",
						uiComponent: "SELECT",
						options: JSON.stringify(["ABA_PAY", "STRIPE", "WING", "CASH"]),
						defaultValue: "ABA_PAY",
						description: "Default gateway preselected on checkout modal",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 3,
						overridden: false,
					},
					{
						id: 804,
						configKey: "finance.vat_tin_number",
						label: "Company Tax / VAT TIN Number",
						configValue: "K008-901823910",
						valueType: "STRING",
						scope: "COMPANY",
						category: "FINANCE",
						uiComponent: "TEXT",
						defaultValue: "K008-901823910",
						description:
							"Official General Department of Taxation registered TIN code",
						isEncrypted: false,
						isReadOnly: false,
						isSystemAdminOnly: false,
						displayOrder: 4,
						overridden: true,
					},
				],
			},
		],
	},
];
